name:  WEI MAO | 茅炜
title: WEI MAO | 茅炜
description: WEI MAO portfolio and blog
tags:
  - blog
  - contemporary art
  - wei mao
  - portfolio
  - art
email: luantty2@gmail.com
disqus_username:
show_hero: true
menu:
  - title: Home
    url: /
  - title: Works
    url: /tags/#work
  - title: About
    url: /about
  - title: Contact
    url: /contact
  # - title: Feed
  #   url: /feed.xml
